#!/bin/bash
#SBATCH --account=PCI_146
#SBATCH --job-name=run_chess
#SBATCH --output=run_chess_%j.out
#SBATCH --error=run_chess__%j.err
#SBATCH --partition=gpunode
#SBATCH --gres=gpu:1        
#SBATCH --ntasks=1          
#SBATCH --cpus-per-task=4   
#SBATCH --time=18:00:00     

module purge

export OCL_ICD_VENDORS=/etc/OpenCL/vendors
export CCL_ROOT=$VIRTUAL_ENV

source /home/mgbalbi/entorno_intel_gpu/bin/activate

python /home/mgbalbi/UNLu-MCTSNN/v2_NN/test_entrenamiento.py
